spring:
  application:
    name: portafolio-inversiones

  datasource:
    url: ${DATABASE_URL}
    driver-class-name: org.postgresql.Driver
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    hikari:
      maximum-pool-size: ${HIKARI_MAX_POOL:5}
      minimum-idle: ${HIKARI_MIN_IDLE:2}
      idle-timeout: 30000
      max-lifetime: 60000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT:5671}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
    virtual-host: ${RABBITMQ_VHOST}
    ssl:
      enabled: true

  mail:
    host: ${SMTP_HOST}
    port: ${SMTP_PORT:587}
    username: ${SMTP_USERNAME}
    password: ${SMTP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enabled:true
    default-encoding: UTF-8

  resend:
    api-key: ${RESEND_API_KEY}

gemini:
  api-key: ${GEMINI_API_KEY}
  modelo: ${GEMINI_MODELO:gemini-3-flash-preview}


claude:
  api-key: {API_KEY_CLAUDE}

jwt:
  secreto: ${JWT_SECRET}
  expiracion-acceso-ms: 900000
  expiracion-refresco-ms: 604800000

cors:
  origenes-permitidos: ${CORS_ORIGINS:http://localhost:5173}

server:
  port: ${PORT:8080}

aws:
  accessKeyId: ${AWS_ACCESS_KEY_ID}
  secretKey: ${AWS_SECRET_ACCESS_KEY}
  region: ${AWS_REGION}
  s3:
    bucket: ${AWS_S3_BUCKET}